# Generated by Django 2.0.7 on 2018-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Firstname',
            field=models.CharField(default='Temidire', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Lastname',
            field=models.CharField(default='Adams', max_length=50),
        ),
    ]
