# Generated by Django 2.0.7 on 2018-12-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20181223_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Lastname',
        ),
    ]
