# Generated by Django 2.0.7 on 2018-12-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_logo', models.ImageField(upload_to='media/product/brands')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=20, null=True)),
                ('catname', models.CharField(max_length=20)),
                ('catImage', models.ImageField(default='me.png', upload_to='efe/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(upload_to='image/products/')),
                ('rearImage', models.ImageField(blank=True, default='default.png', upload_to='image/products/')),
                ('frontImage', models.ImageField(blank=True, default='default.png', upload_to='image/products/')),
                ('prodname', models.CharField(help_text='max of 30 characters', max_length=30)),
                ('price', models.FloatField()),
                ('numbers', models.IntegerField()),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('Dimension', models.TextField()),
                ('material', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.brand')),
                ('categories', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.categories')),
            ],
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='Product.size'),
        ),
    ]
