# Generated by Django 2.0.7 on 2018-12-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20181215_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.gender'),
        ),
    ]
