# Generated by Django 2.0.7 on 2018-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20181216_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numbers',
            field=models.PositiveIntegerField(),
        ),
    ]
