# Generated by Django 2.0.7 on 2018-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20181216_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='gender_image',
            field=models.ImageField(default='default.png', upload_to='gender'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='catImage',
            field=models.ImageField(default='me.png', upload_to='category'),
        ),
    ]
