# Generated by Django 2.0.7 on 2018-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20181226_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='description',
            field=models.TextField(default='gender'),
        ),
    ]
