# Generated by Django 2.0.7 on 2018-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_gender_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='category',
            field=models.ManyToManyField(blank=True, to='Product.categories'),
        ),
    ]
