# Generated by Django 2.0.7 on 2019-01-16 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20181229_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='shelve',
            field=models.ImageField(default='me.png', upload_to='category/shelve'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.Gender'),
        ),
    ]
