# Generated by Django 2.0.7 on 2018-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(default='me.png', upload_to='ammat/')),
                ('about', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('facebook', models.TextField()),
                ('Twitter', models.CharField(max_length=20)),
                ('youtube', models.TextField()),
            ],
        ),
    ]
